# @package _global_
algorithm: shac
updates: 100
save_interval: 50
shac:
  horizon: 32
  actor_learning_rate: 0.001
  critic_learning_rate: 0.001
  gamma: 0.99
  td_lambda: 0.95
  entropy_weight: 0.0
  actor_max_grad_norm: 1.0
  critic_max_grad_norm: 1.0
  critic_minibatches: 8
  critic_iterations: 1
  target_update_rate: 0.005
  log_standard_deviation_min: -5.0
  log_standard_deviation_max: -1.0
